<?php

/**
 * @file
 * Contains social_feed.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_feed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_feed module.
    case 'help.page.social_feed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function social_feed_theme() {
  return [
    // Social feed theme.
    'social_feed' => [
      'render element' => 'children',
      // Variables passed to social_feed.
      'variables' => [
        'instagramurl' => NULL,
        'instagramurlpost' => NULL,
        'facebookurl' => NULL,
        'facebooktext' => NULL,
        'facebookimage' => NULL,
        'twittertext' => NULL,
        'twitteruser' => NULL,
        'twitterurl' => NULL,
      ],
    ],
  ];
}

/**
 * Attach libraries.
 */
function social_feed_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'social_feed/social_feed';
}
