features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
  path: 'public://123.png'
favicon:
  use_default: true
  path: 'public://123_0.png'
  mimetype: image/png
