palette:
  top: '#ff3333'
  bottom: '#ffffff'
  bg: '#fffdf7'
  sidebar: '#edede7'
  sidebarborders: '#e7e7e7'
  footer: '#2c2c28'
  titleslogan: '#ffffff'
  text: '#301313'
  link: '#9d408d'
logo: 'public://color/bartik-75b4ad0b/logo.svg'
stylesheets:
  - 'public://color/bartik-75b4ad0b/colors.css'
files:
  - 'public://color/bartik-75b4ad0b/logo.svg'
  - 'public://color/bartik-75b4ad0b/colors.css'
