horizontal_menu: racc-nav-bottom
horizontal_depth: 9
off_canvas_menus: racc-nav-bottom
horizontal_wrapping_element: nav
horizontal_breakpoint: wide
horizontal_media_query: 'all and (min-width: 851px)'
include_css: true
off_canvas_position: right
off_canvas_theme: theme-white
horizontal_superfish: true
horizontal_superfish_delay: 300
horizontal_superfish_speed: 100
horizontal_superfish_speed_out: 100
horizontal_superfish_hoverintent: true
hammerjs: true
breakpoint_css_filepath: 'public://css'
use_breakpoint: true
_core:
  default_config_hash: XSKdMLR7vuHUhp56C8BBAHX-WiKaMFwAFQsFelPjUVk
